// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeQ5b770UJcz2CZTy0b-f2NP46tYR8Y3g',
    appId: '1:618391055781:web:09eed7ff66206af3264c4c',
    messagingSenderId: '618391055781',
    projectId: 'cuoiki-14afd',
    authDomain: 'cuoiki-14afd.firebaseapp.com',
    databaseURL: 'https://cuoiki-14afd-default-rtdb.firebaseio.com',
    storageBucket: 'cuoiki-14afd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAijdB8gEbjdnq9e1DzQweOxAL_F44ysws',
    appId: '1:618391055781:android:1716803fa07135b6264c4c',
    messagingSenderId: '618391055781',
    projectId: 'cuoiki-14afd',
    databaseURL: 'https://cuoiki-14afd-default-rtdb.firebaseio.com',
    storageBucket: 'cuoiki-14afd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrWu1hpB3yxj2_K8Z02LjfgOwBltcmzqU',
    appId: '1:618391055781:ios:94538bd0acbc5ebc264c4c',
    messagingSenderId: '618391055781',
    projectId: 'cuoiki-14afd',
    databaseURL: 'https://cuoiki-14afd-default-rtdb.firebaseio.com',
    storageBucket: 'cuoiki-14afd.appspot.com',
    androidClientId: '618391055781-58enfcnq4igka9b4s3ntlge0l91h6oah.apps.googleusercontent.com',
    iosClientId: '618391055781-98iouvtup1lv2q9sel14e4rq03kj5ar8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoginApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrWu1hpB3yxj2_K8Z02LjfgOwBltcmzqU',
    appId: '1:618391055781:ios:94538bd0acbc5ebc264c4c',
    messagingSenderId: '618391055781',
    projectId: 'cuoiki-14afd',
    databaseURL: 'https://cuoiki-14afd-default-rtdb.firebaseio.com',
    storageBucket: 'cuoiki-14afd.appspot.com',
    androidClientId: '618391055781-58enfcnq4igka9b4s3ntlge0l91h6oah.apps.googleusercontent.com',
    iosClientId: '618391055781-98iouvtup1lv2q9sel14e4rq03kj5ar8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoginApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeQ5b770UJcz2CZTy0b-f2NP46tYR8Y3g',
    appId: '1:618391055781:web:af59626c66d6aee1264c4c',
    messagingSenderId: '618391055781',
    projectId: 'cuoiki-14afd',
    authDomain: 'cuoiki-14afd.firebaseapp.com',
    databaseURL: 'https://cuoiki-14afd-default-rtdb.firebaseio.com',
    storageBucket: 'cuoiki-14afd.appspot.com',
  );

}